apiVersion: v1
kind: Service
metadata:
  namespace: sonarqube
  name: sonarqube
  labels:
    app: sonarqube
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
    - name: tcp
      protocol: TCP
      port: 9000
