apiVersion: v1
kind: Service
metadata:
  namespace: sql
  name: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
